// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/client_info.proto

package ru.spbau.lupuleac.app;

public final class ClientInfoProtocol {
  private ClientInfoProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 port = 1;</code>
     */
    boolean hasPort();
    /**
     * <code>required int32 port = 1;</code>
     */
    int getPort();

    /**
     * <code>required int32 number_of_clients = 2;</code>
     */
    boolean hasNumberOfClients();
    /**
     * <code>required int32 number_of_clients = 2;</code>
     */
    int getNumberOfClients();

    /**
     * <code>required int32 queries_per_client = 3;</code>
     */
    boolean hasQueriesPerClient();
    /**
     * <code>required int32 queries_per_client = 3;</code>
     */
    int getQueriesPerClient();

    /**
     * <code>required int32 elements_in_array = 4;</code>
     */
    boolean hasElementsInArray();
    /**
     * <code>required int32 elements_in_array = 4;</code>
     */
    int getElementsInArray();

    /**
     * <code>required int32 time_interval = 5;</code>
     */
    boolean hasTimeInterval();
    /**
     * <code>required int32 time_interval = 5;</code>
     */
    int getTimeInterval();

    /**
     * <code>required string host = 6;</code>
     */
    boolean hasHost();
    /**
     * <code>required string host = 6;</code>
     */
    java.lang.String getHost();
    /**
     * <code>required string host = 6;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();
  }
  /**
   * Protobuf type {@code ClientInfo}
   */
  public  static final class ClientInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClientInfo)
      ClientInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientInfo.newBuilder() to construct.
    private ClientInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientInfo() {
      port_ = 0;
      numberOfClients_ = 0;
      queriesPerClient_ = 0;
      elementsInArray_ = 0;
      timeInterval_ = 0;
      host_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              port_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              numberOfClients_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              queriesPerClient_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              elementsInArray_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timeInterval_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              host_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.spbau.lupuleac.app.ClientInfoProtocol.internal_static_ClientInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.spbau.lupuleac.app.ClientInfoProtocol.internal_static_ClientInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo.class, ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo.Builder.class);
    }

    private int bitField0_;
    public static final int PORT_FIELD_NUMBER = 1;
    private int port_;
    /**
     * <code>required int32 port = 1;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 port = 1;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int NUMBER_OF_CLIENTS_FIELD_NUMBER = 2;
    private int numberOfClients_;
    /**
     * <code>required int32 number_of_clients = 2;</code>
     */
    public boolean hasNumberOfClients() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 number_of_clients = 2;</code>
     */
    public int getNumberOfClients() {
      return numberOfClients_;
    }

    public static final int QUERIES_PER_CLIENT_FIELD_NUMBER = 3;
    private int queriesPerClient_;
    /**
     * <code>required int32 queries_per_client = 3;</code>
     */
    public boolean hasQueriesPerClient() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 queries_per_client = 3;</code>
     */
    public int getQueriesPerClient() {
      return queriesPerClient_;
    }

    public static final int ELEMENTS_IN_ARRAY_FIELD_NUMBER = 4;
    private int elementsInArray_;
    /**
     * <code>required int32 elements_in_array = 4;</code>
     */
    public boolean hasElementsInArray() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 elements_in_array = 4;</code>
     */
    public int getElementsInArray() {
      return elementsInArray_;
    }

    public static final int TIME_INTERVAL_FIELD_NUMBER = 5;
    private int timeInterval_;
    /**
     * <code>required int32 time_interval = 5;</code>
     */
    public boolean hasTimeInterval() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 time_interval = 5;</code>
     */
    public int getTimeInterval() {
      return timeInterval_;
    }

    public static final int HOST_FIELD_NUMBER = 6;
    private volatile java.lang.Object host_;
    /**
     * <code>required string host = 6;</code>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string host = 6;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          host_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string host = 6;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNumberOfClients()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQueriesPerClient()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasElementsInArray()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeInterval()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, port_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, numberOfClients_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, queriesPerClient_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, elementsInArray_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, timeInterval_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, host_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, port_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, numberOfClients_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, queriesPerClient_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, elementsInArray_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, timeInterval_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, host_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo)) {
        return super.equals(obj);
      }
      ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo other = (ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo) obj;

      boolean result = true;
      result = result && (hasPort() == other.hasPort());
      if (hasPort()) {
        result = result && (getPort()
            == other.getPort());
      }
      result = result && (hasNumberOfClients() == other.hasNumberOfClients());
      if (hasNumberOfClients()) {
        result = result && (getNumberOfClients()
            == other.getNumberOfClients());
      }
      result = result && (hasQueriesPerClient() == other.hasQueriesPerClient());
      if (hasQueriesPerClient()) {
        result = result && (getQueriesPerClient()
            == other.getQueriesPerClient());
      }
      result = result && (hasElementsInArray() == other.hasElementsInArray());
      if (hasElementsInArray()) {
        result = result && (getElementsInArray()
            == other.getElementsInArray());
      }
      result = result && (hasTimeInterval() == other.hasTimeInterval());
      if (hasTimeInterval()) {
        result = result && (getTimeInterval()
            == other.getTimeInterval());
      }
      result = result && (hasHost() == other.hasHost());
      if (hasHost()) {
        result = result && getHost()
            .equals(other.getHost());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPort()) {
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
      }
      if (hasNumberOfClients()) {
        hash = (37 * hash) + NUMBER_OF_CLIENTS_FIELD_NUMBER;
        hash = (53 * hash) + getNumberOfClients();
      }
      if (hasQueriesPerClient()) {
        hash = (37 * hash) + QUERIES_PER_CLIENT_FIELD_NUMBER;
        hash = (53 * hash) + getQueriesPerClient();
      }
      if (hasElementsInArray()) {
        hash = (37 * hash) + ELEMENTS_IN_ARRAY_FIELD_NUMBER;
        hash = (53 * hash) + getElementsInArray();
      }
      if (hasTimeInterval()) {
        hash = (37 * hash) + TIME_INTERVAL_FIELD_NUMBER;
        hash = (53 * hash) + getTimeInterval();
      }
      if (hasHost()) {
        hash = (37 * hash) + HOST_FIELD_NUMBER;
        hash = (53 * hash) + getHost().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientInfo)
        ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.spbau.lupuleac.app.ClientInfoProtocol.internal_static_ClientInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.spbau.lupuleac.app.ClientInfoProtocol.internal_static_ClientInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo.class, ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo.Builder.class);
      }

      // Construct using ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        numberOfClients_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        queriesPerClient_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        elementsInArray_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        timeInterval_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        host_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.spbau.lupuleac.app.ClientInfoProtocol.internal_static_ClientInfo_descriptor;
      }

      public ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo getDefaultInstanceForType() {
        return ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo.getDefaultInstance();
      }

      public ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo build() {
        ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo buildPartial() {
        ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo result = new ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.numberOfClients_ = numberOfClients_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.queriesPerClient_ = queriesPerClient_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.elementsInArray_ = elementsInArray_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timeInterval_ = timeInterval_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.host_ = host_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo) {
          return mergeFrom((ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo other) {
        if (other == ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo.getDefaultInstance()) return this;
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasNumberOfClients()) {
          setNumberOfClients(other.getNumberOfClients());
        }
        if (other.hasQueriesPerClient()) {
          setQueriesPerClient(other.getQueriesPerClient());
        }
        if (other.hasElementsInArray()) {
          setElementsInArray(other.getElementsInArray());
        }
        if (other.hasTimeInterval()) {
          setTimeInterval(other.getTimeInterval());
        }
        if (other.hasHost()) {
          bitField0_ |= 0x00000020;
          host_ = other.host_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPort()) {
          return false;
        }
        if (!hasNumberOfClients()) {
          return false;
        }
        if (!hasQueriesPerClient()) {
          return false;
        }
        if (!hasElementsInArray()) {
          return false;
        }
        if (!hasTimeInterval()) {
          return false;
        }
        if (!hasHost()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int port_ ;
      /**
       * <code>required int32 port = 1;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 port = 1;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required int32 port = 1;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000001;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 port = 1;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        onChanged();
        return this;
      }

      private int numberOfClients_ ;
      /**
       * <code>required int32 number_of_clients = 2;</code>
       */
      public boolean hasNumberOfClients() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 number_of_clients = 2;</code>
       */
      public int getNumberOfClients() {
        return numberOfClients_;
      }
      /**
       * <code>required int32 number_of_clients = 2;</code>
       */
      public Builder setNumberOfClients(int value) {
        bitField0_ |= 0x00000002;
        numberOfClients_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 number_of_clients = 2;</code>
       */
      public Builder clearNumberOfClients() {
        bitField0_ = (bitField0_ & ~0x00000002);
        numberOfClients_ = 0;
        onChanged();
        return this;
      }

      private int queriesPerClient_ ;
      /**
       * <code>required int32 queries_per_client = 3;</code>
       */
      public boolean hasQueriesPerClient() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 queries_per_client = 3;</code>
       */
      public int getQueriesPerClient() {
        return queriesPerClient_;
      }
      /**
       * <code>required int32 queries_per_client = 3;</code>
       */
      public Builder setQueriesPerClient(int value) {
        bitField0_ |= 0x00000004;
        queriesPerClient_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 queries_per_client = 3;</code>
       */
      public Builder clearQueriesPerClient() {
        bitField0_ = (bitField0_ & ~0x00000004);
        queriesPerClient_ = 0;
        onChanged();
        return this;
      }

      private int elementsInArray_ ;
      /**
       * <code>required int32 elements_in_array = 4;</code>
       */
      public boolean hasElementsInArray() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 elements_in_array = 4;</code>
       */
      public int getElementsInArray() {
        return elementsInArray_;
      }
      /**
       * <code>required int32 elements_in_array = 4;</code>
       */
      public Builder setElementsInArray(int value) {
        bitField0_ |= 0x00000008;
        elementsInArray_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 elements_in_array = 4;</code>
       */
      public Builder clearElementsInArray() {
        bitField0_ = (bitField0_ & ~0x00000008);
        elementsInArray_ = 0;
        onChanged();
        return this;
      }

      private int timeInterval_ ;
      /**
       * <code>required int32 time_interval = 5;</code>
       */
      public boolean hasTimeInterval() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 time_interval = 5;</code>
       */
      public int getTimeInterval() {
        return timeInterval_;
      }
      /**
       * <code>required int32 time_interval = 5;</code>
       */
      public Builder setTimeInterval(int value) {
        bitField0_ |= 0x00000010;
        timeInterval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 time_interval = 5;</code>
       */
      public Builder clearTimeInterval() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timeInterval_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>required string host = 6;</code>
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string host = 6;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            host_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string host = 6;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string host = 6;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 6;</code>
       */
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000020);
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 6;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        host_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClientInfo)
    }

    // @@protoc_insertion_point(class_scope:ClientInfo)
    private static final ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo();
    }

    public static ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ClientInfo>
        PARSER = new com.google.protobuf.AbstractParser<ClientInfo>() {
      public ClientInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientInfo> getParserForType() {
      return PARSER;
    }

    public ru.spbau.lupuleac.app.ClientInfoProtocol.ClientInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$src/main/resources/client_info.proto\"\221" +
      "\001\n\nClientInfo\022\014\n\004port\030\001 \002(\005\022\031\n\021number_of" +
      "_clients\030\002 \002(\005\022\032\n\022queries_per_client\030\003 \002" +
      "(\005\022\031\n\021elements_in_array\030\004 \002(\005\022\025\n\rtime_in" +
      "terval\030\005 \002(\005\022\014\n\004host\030\006 \002(\tB+\n\025ru.spbau.l" +
      "upuleac.appB\022ClientInfoProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ClientInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientInfo_descriptor,
        new java.lang.String[] { "Port", "NumberOfClients", "QueriesPerClient", "ElementsInArray", "TimeInterval", "Host", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
